universe = vanilla
executable = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/launchBilby_reruns.sh
arguments = $(jobNumber) $(json) $(outdir)
notification = error
accounting_group = ligo.dev.o3.cbc.bayesianpopulations.parametric
RequestMemory = 20000
RequestDisk = 500000
log = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/logs/pop1/job_$(jobNumber)_rerun.log
output = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/logs/pop1/job_$(jobNumber)_rerun.out
error = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/logs/pop1/job_$(jobNumber)_rerun.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue 1
