universe = vanilla
executable = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/launchBilby_fixedExtrinsic2.sh
arguments = $(jobNumber) $(json) $(outdir)
notification = error
accounting_group = ligo.dev.o4.cbc.bayesianpopulations.parametric
RequestMemory = 20000
RequestDisk = 500000
log = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/new_bilby/logs/pop1/job_$(jobNumber)_fixedExtrinsic.log
output = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/new_bilby/logs/pop1/job_$(jobNumber)_fixedExtrinsic.out
error = /home/simona.miller/comp-spin-mock-injections/Code/IndividualInference/condor/new_bilby/logs/pop1/job_$(jobNumber)_fixedExtrinsic.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue 1
